tsdf_voxel_size: 0.05
truncation_distance: 0.15
max_weight: 1000
pointcloud_queue_size: 10
max_ray_length_m: 4 # 14 or 16m would be better, but for that we need better odometry. Otherwise the surface get too damaged.
min_ray_length_m: 0.1
max_consecutive_ray_collisions: 10
use_const_weight: true
use_weight_dropoff: false
use_sparsity_compensation_factor: true
sparsity_compensation_factor: 20.0

esdf_max_distance: 4
esdf_min_distance: 0.1

publish_maps_every_n_sec: 1.0
loop_closure_topic: "/loop_closure_in"