node_names: ["/coxgraph/coxgraph_client_0", "/tsdf_client/label_tsdf_client_0", "/pose_graph_backend", "/coxgraph/coxgraph_server_node"]
node_eval_mode:  [["cpu","mem"], ["cpu","mem"], ["cpu","mem"], ["cpu","mem"]]

topic_eval_mode: [["topic_bw"],["topic_bw"]]
topic_names: ["/tsdf_client/label_tsdf_client_0/tsdf_map_out", "/firefly_0/pose_graph_0/vins_keyframe"]

plot_dir: "/workspaces/voxgraph_melodic_ws/eval/node_evaluator"