verbose: true
client_number: 2

tsdf_voxel_size: 0.05
tsdf_voxels_per_size: 16

map_fusion_topic: "/ccmslam/map_fusion_out"
map_fusion_queue_size: 1

client_name_prefix: "coxgraph_client_"
client_loop_closure_topic: "loop_closure_in"
ch_pub_queue_length: 10