# Experiment (Maze) specific parameters

# Bounding boxes (in initialization frame, relative to PlayerStart)
map_bounding_volume:
  x_min: -20.0
  x_max: 20.0
  y_min: -20.0
  y_max: 20.0
  z_min: 0
  z_max: 3

evaluation_bounding_volum:
  x_min: -20.0
  x_max: 20.0
  y_min: -20.0
  y_max: 20.0
  z_min: 0
  z_max: 3

target_bounding_volume:
  x_min: 0
  x_max: 15
  y_min: 0
  y_max: 15
  z_min: 1
  z_max: 2

# System Constraints
planner:
  system_constraints:
    v_max: 0.5
    a_max: 0.5
    yaw_rate_max: 1.57
