num_agents: 2
world_frame: "world"
odom_frame: "odom"
agent_frame: "agent"
publish_pcl_world: true

agent_0:
  namespace: "firefly_0"
  position: [0.0, 0.0, 2.0] # Position of the reference frame [m]
  yaw: 0.0 # Orientation of reference frame [deg]
  random_walk_mean_pos: 0.0
  random_walk_cov_pos: 0.00003
  random_walk_mean_ang: 0.0
  random_walk_cov_ang: 0.000075

agent_1:
  namespace: "firefly_1"
  position: [1.0, 1.0, 2.0] # Position of the reference frame [m]
  yaw: 0.0 # Orientation of reference frame [deg]
  random_walk_mean_pos: 0.0
  random_walk_cov_pos: 0.00003
  random_walk_mean_ang: 0.0
  random_walk_cov_ang: 0.000075
